

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
version: 2

sources:
  - name: Ecommerce_Sales
    database: '"Ecommerce Sales"'  # Enclose in double quotes
    schema: PUBLIC
    tables:
      - name: SALES

